import enum


class MembershipRole(str, enum.Enum):
    OWNER = "OWNER"
    MANAGER = "MANAGER"
    EMPLOYEE = "EMPLOYEE"


class ShiftStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    CANCELLED = "CANCELLED"


class TimeOffStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class ShiftSwapRequestType(str, enum.Enum):
    GIVE_UP = "GIVE_UP"
    SWAP = "SWAP"


class ShiftSwapStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class AuditAction(str, enum.Enum):
    SHIFT_SWAP_REQUESTED = "SHIFT_SWAP_REQUESTED"
    SHIFT_SWAP_APPROVED = "SHIFT_SWAP_APPROVED"
    SHIFT_SWAP_REJECTED = "SHIFT_SWAP_REJECTED"
    SCHEDULE_GENERATED = "SCHEDULE_GENERATED"
    SCHEDULE_PUBLISHED = "SCHEDULE_PUBLISHED"
    TIME_OFF_APPROVED = "TIME_OFF_APPROVED"
    TIME_OFF_REJECTED = "TIME_OFF_REJECTED"


class DocumentType(str, enum.Enum):
    TRAINING_CERTIFICATE = "TRAINING_CERTIFICATE"
    FOOD_SAFETY_CERTIFICATE = "FOOD_SAFETY_CERTIFICATE"
    CPR_CERTIFICATE = "CPR_CERTIFICATE"
    SIGNED_EMPLOYMENT_FORM = "SIGNED_EMPLOYMENT_FORM"
    ID_WORK_AUTHORIZATION = "ID_WORK_AUTHORIZATION"
